"""Render the reviewed maker dataset as crawlable MkDocs pages. No network at build time."""
from __future__ import annotations

import argparse
import json
import re
from html import escape
from pathlib import Path
from urllib.parse import urlsplit

import yaml
import material

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs/assets/data/makers.yml"
DEST = ROOT / "docs/zh-Hans/makers"
ASSETS = ROOT / "docs/assets/images/makers"
STATUS = {"sales": "公开销售", "inquiry": "接受询价", "lottery": "周期抽选", "paused": "暂停定制", "unverified": "接单待核实"}
ACTIVE = {"sales", "inquiry", "lottery"}


def confirmed_platforms(maker):
    return list(dict.fromkeys(c[0] for c in maker["channels"] if not c[3].startswith("第三方")))


def esc(value):
    return escape(str(value), quote=True)


def link(label, url):
    if urlsplit(url).scheme not in {"https", "http", "mailto", "tel"}:
        raise ValueError(f"Unsupported public URL: {url}")
    return f'<a href="{esc(url)}" rel="noopener noreferrer">{esc(label)}</a>'


def ref(maker, key):
    if key not in maker["sources"]:
        raise ValueError(f"Missing source {key} for {maker['id']}")
    return f'<a href="#source-{esc(key)}">来源</a>'


def image_path(maker, kind):
    paths = sorted(ASSETS.glob(f"{maker['id']}-{kind}.*"))
    paths = [path for path in paths if path.suffix != ".json"]
    return paths[0] if paths else None


def logo(maker, depth):
    path = image_path(maker, "logo")
    if path:
        return f'<img class="maker-logo" src="/assets/images/makers/{esc(path.name)}" alt="{esc(maker["name"])} 品牌识别图" width="88" height="60" loading="lazy">'
    return '<span class="maker-logo maker-logo--missing" aria-label="未收录官方图标">暂无图标</span>'


def table(headers, rows, css="maker-table"):
    head = "".join(f"<th scope=\"col\">{esc(x)}</th>" for x in headers)
    body = "".join("<tr>" + "".join(f"<td>{x}</td>" for x in row) + "</tr>" for row in rows)
    return f'<div class="maker-table-scroll" tabindex="0" role="region" aria-label="{esc(headers[0])}表"><table class="{css}"><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def detail(maker, checked):
    name = maker["name"]
    lines = ["---", f"title: {json.dumps(name, ensure_ascii=False)}", f"description: {json.dumps(maker['summary'], ensure_ascii=False)}", "---", "", "<!-- Generated by scripts/build_makers.py; edit docs/assets/data/makers.yml. -->", "",
             '<p class="maker-back"><a href="../">:material-arrow-left: 头壳店铺目录</a></p>', "",
             '<div class="maker-profile-heading">', logo(maker, 4), '<div>',
             f'<p class="archive-kicker">MAKER RECORD / {esc(maker["id"].upper())}</p>',
             f'<h1>{esc(name)}</h1>', f'<p>{esc(maker["summary"])}</p>', '</div></div>', "",
             f'<p class="maker-record-meta"><span class="maker-status maker-status--{maker["status"]}">{STATUS[maker["status"]]}</span>网页核实 {checked} · 来源见文末</p>', "",
             f'> **营业证据**：{maker["status_note"]}', "", "## 店铺介绍", "", maker["description"], "",
             table(["基本信息", "公开记录"], [["所在地区", esc(maker["location"])], ["名称与别名", esc(" / ".join(maker["aliases"]))], ["商品与服务", esc(" · ".join(maker["categories"]))], ["核实日期", checked]]), ""]
    if maker.get("address"):
        lines += [maker["address"], ""]
    photo = image_path(maker, "photo")
    if photo:
        lines += [f'<figure class="maker-product-photo"><img src="/assets/images/makers/{photo.name}" alt="{esc(maker["photo_caption"])}" width="640" height="800" loading="lazy"><figcaption>{esc(maker["photo_caption"])} {ref(maker, maker["photo_source"])}</figcaption></figure>', ""]
    lines += ["## 官方入口与平台归属", "", table(["平台", "店铺 / 入口", "归属证据", "依据"], [[esc(platform), link(title, url), esc(evidence), ref(maker, source)] for platform, title, url, evidence, source in maker["channels"]]), "", "## 公开联系方式", "", table(["渠道", "公开业务联系方式", "依据"], [[esc(kind), link(value, url), ref(maker, source)] for kind, value, url, source in maker["contacts"]]), "", "## 商品与价格", "", "以下为核实当日公开页面记录，保留原币；不跨币种换算，不把订金、素体或配件当作完整头壳价格。未逐个完成下单，库存及最终配置以店铺确认为准。", "",
              table(["商品名称", "分类", "公开价格", "价格性质", "配置 / 状态", "依据"], [[esc(title), esc(kind), esc(f"{currency} {amount}".strip()) if amount else "未公开", esc(basis), esc(note), ref(maker, source)] for title, kind, currency, amount, basis, note, source in maker["products"]]), "", "## 订购与服务", "", maker["terms"], "", "## 跨平台复核", "", maker["merge_note"], ""]
    if maker["id"] in {"umoon", "hidolls", "blackcat"}:
        path = "../../digests/2026-08/index.md" if maker["id"] == "umoon" else "../../years/2025/index.md"
        lines += [f"本站关联记录：[{'2026 年 8 月采集' if maker['id'] == 'umoon' else '2025 年编年史'}]({path})。历史活动资料仅作背景，不作为本次营业证明。", ""]
    lines += ["## 来源与图像", "", f"本档案整理于 **{checked}**；来源标题区分本轮已读取网页、官方链接与历史线索。列出链接不代表已读取所有目标页面或验证平台库存；社群目录为 2025 年版本，不代表当前营业状态。店家描述已重新组织，材料与服务承诺仍为店方自述。", ""]
    for key, (label, url) in maker["sources"].items():
        lines += [f'<p id="source-{esc(key)}">{link(label, url)}</p>', ""]
    if maker.get("logo"):
        lines += [f'品牌识别图来自 {link("官方公开图片", maker["logo"])}（{ref(maker, maker["logo_source"])}），仅用于店铺识别，权利归原权利人。图片未获得开放许可，不属于本站原创内容授权范围。', ""]
    if maker.get("logo_note"):
        lines += [maker["logo_note"], ""]
    lines += ["未查到的电话、微信、详细地址及平台账号不作推测；需要补证的字段不代表该信息不存在。", "", "[返回店铺目录](../index.md) · [收录、去重与平台核实](methodology.md)".replace("(methodology.md)", "(../methodology.md)"), ""]
    return "\n".join(lines)


def index(makers, checked):
    total = len(makers)
    active = sum(m["status"] in ACTIVE for m in makers)
    regions = list(dict.fromkeys(m["region"] for m in makers))
    platforms = list(dict.fromkeys(p for m in makers for p in confirmed_platforms(m)))
    options = lambda values: "".join(f'<option value="{esc(v)}">{esc(v)}</option>' for v in values)
    lines = ["---", "title: 头壳店铺", "description: 按店铺归并的国内外 animegao kigurumi 头壳制作目录，含公开联系方式、原币价格、营业证据和来源。", "hide:", "  - toc", "---", "", "<!-- Generated by scripts/build_makers.py; edit docs/assets/data/makers.yml. -->", "",
             '<section class="maker-intro">', '<p class="archive-kicker">KIGURUMI / MAKER DIRECTORY</p>', '<h1>头壳店铺</h1>', '<p>国内与海外的 animegao kigurumi 头壳制作者。<br>按店铺归档，沿公开来源了解作品、价格与委托方式。</p>', f'<p class="maker-updated">资料核实 · {checked} <a href="methodology/">收录与复核说明 :material-arrow-top-right:</a></p>', '</section>', "",
             '<div class="maker-stats">', f'<div><strong>{active:02}</strong><span>有公开销售 / 询价入口</span></div><div><strong>{total:02}</strong><span>独立店铺档案</span></div><div><strong>{len(regions) - ("地区待核实" in regions):02}</strong><span>地区分组</span></div>', '</div>', "",
             '<p class="maker-scope">仅收录人脸 / 动漫角色头壳。Furry 兽头、兽装及连体睡衣不在本目录范围内；混合经营店铺仅记录符合范围的商品。</p>', "",
             '<div class="maker-directory" data-maker-directory>', '<form class="maker-filters" role="search" aria-label="筛选头壳店铺">',
             '<label class="maker-search"><span>搜索店铺</span><input type="search" name="q" placeholder="名称、别名、型号或公开联系方式" autocomplete="off"></label>',
             f'<label><span>所在地区</span><select name="region"><option value="">全部地区</option>{options(regions)}</select></label>',
             '<label><span>营业证据</span><select name="status"><option value="active">公开销售 / 接受询价</option><option value="all">全部档案</option>' + "".join(f'<option value="{k}">{v}</option>' for k, v in STATUS.items()) + '</select></label>',
             '<label><span>商品类型</span><select name="category"><option value="">全部类型</option>' + options(sorted(set(c for m in makers for c in m["categories"]))) + '</select></label>',
             '<label><span>官方提及渠道</span><select name="platform"><option value="">全部渠道</option>' + options(platforms) + '</select></label>',
             '<button type="reset" class="maker-reset" aria-label="重置筛选" title="重置筛选">:material-filter-remove-outline:</button>', '</form>',
             f'<div class="maker-results-bar"><p data-maker-count role="status" aria-live="polite">{active} 家符合条件 / 共 {total} 份档案</p><a href="/assets/data/makers.json" download>:material-download: 下载完整数据</a></div>',
             '<div class="maker-list-head" aria-hidden="true"><span>店铺 / 品牌</span><span>所在地区</span><span>商品与服务</span><span>公开价格摘要</span><span>营业证据</span></div>', '<ul class="maker-list">']
    # Keep the featured set in a stable editorial order, independent of source URL order.
    order = {key: i for i, key in enumerate(["meis", "heyao", "bhy", "blackcat", "hidolls", "kigland", "gko", "sigma", "munimuni", "dame", "teitoku", "kaga", "kigcos", "middream", "sensei", "umoon"])}
    for maker in sorted(makers, key=lambda m: order.get(m["id"], total)):
        query = " ".join([maker["name"], *maker["aliases"], maker["summary"], maker["location"], *[p[0] for p in maker["products"]], *[c[1] for c in maker["contacts"]]])
        maker_platforms = confirmed_platforms(maker)
        hidden = " hidden" if maker["status"] not in ACTIVE else ""
        lines += [f'<li class="maker-row" data-search="{esc(query)}" data-region="{esc(maker["region"])}" data-status="{maker["status"]}" data-category="{esc("|".join(maker["categories"]))}" data-platform="{esc("|".join(maker_platforms))}"{hidden}>',
                  f'<a class="maker-row-link" href="{maker["id"]}/" aria-label="查看 {esc(maker["name"])} 的店铺档案">',
                  f'<span class="maker-identity">{logo(maker, 3)}<span><strong>{esc(maker["name"])}</strong><small>{esc(maker["summary"])}</small></span></span>',
                  f'<span class="maker-region"><span class="maker-mobile-label">地区</span>{esc(maker["region"])}</span>',
                  f'<span class="maker-categories"><span class="maker-mobile-label">类型</span>{esc(" / ".join(maker["categories"][:2]))}</span>',
                  f'<span class="maker-price"><span class="maker-mobile-label">价格</span>{esc(maker["price_summary"])}</span>',
                  f'<span class="maker-row-end"><span class="maker-status maker-status--{maker["status"]}">{STATUS[maker["status"]]}</span><span class="maker-arrow" aria-hidden="true">:material-arrow-right:</span></span>', '</a></li>']
    other_records = '、'.join(f'<a href="{m["id"]}/">{esc(m["name"])}（{STATUS[m["status"]]}）</a>' for m in makers if m["status"] not in ACTIVE)
    lines += ['</ul>', '<div class="maker-empty" data-maker-empty hidden><h2>没有匹配的店铺</h2><p>当前筛选结果为 0 家。</p><button type="button" data-maker-clear>清除筛选</button></div>', '</div>', "",
              f'<noscript><p>另有暂停及待核实档案：{other_records}。</p></noscript>', "",
              '## 本次复核', "", '**“公开销售 / 接受询价”代表第一方网页有商业入口，不等同于已经验证可立即接单、现货库存或交易履约。** 原币金额是核实时的公开快照，订金、配件及停产余货分别标注。', "",
              '- 猫豆腐、虾饺工房、底层人员及抛瓦均有官方淘宝／闲鱼店名声明；平台 UID、库存及价格另行核实。底层人员与抛瓦分别建档。', '- 官方提及渠道包括已提供链接与只声明店名两种，详情逐项标注；第三方历史关联不计入这一筛选。', '- 莓萌与拼好头合并；与偶域保持独立。KigLover 更名为 MidDreamKigu。', '- 冉月新增进店咨询与业务群证据；哆啦、新颜、哈卡的新单状态待确认，Kigurumi Sensei 暂停定制。', '- 深海工坊夏季促销已结束，哈卡历史均价及星玥琦单日促销不作为当前报价。', '- HiDolls 的 Animal 系列不收录；Mirrodoll 当前域名转为宠物盲盒，不作为头壳营业证据。', "",
              '[查看平台覆盖、待复核线索与去重依据](methodology.md) · [地点目录](../places/index.md) · [提交补充或勘误](../join/index.md)', ""]
    return "\n".join(lines)


def validate(data):
    ids = set()
    for maker in data["makers"]:
        assert re.fullmatch(r"[a-z0-9-]+", maker["id"]), maker["id"]
        assert maker["id"] not in ids, f"Duplicate maker: {maker['id']}"
        ids.add(maker["id"])
        assert maker["status"] in STATUS
        for source in maker["sources"].values():
            assert len(source) == 2
            link(*source)
        for product in maker["products"]:
            assert len(product) == 7, product
            ref(maker, product[-1])
            assert product[2] in {"", "CNY", "USD", "JPY", "GBP", "HKD", "EUR"}
        for channel in maker["channels"]:
            assert len(channel) == 5
            ref(maker, channel[-1])
        for contact in maker["contacts"]:
            assert len(contact) == 4
            ref(maker, contact[-1])


def render(check=False):
    data = yaml.safe_load(DATA.read_text())
    validate(data)
    files = {DEST / "index.md": index(data["makers"], data["checked"])}
    files.update({DEST / m["id"] / "index.md": detail(m, data["checked"]) for m in data["makers"]})
    exported = {"checked": data["checked"], "scope": data["scope"], "status_labels": STATUS,
                "product_fields": ["name", "category", "currency", "amount", "price_basis", "note", "source_id"],
                "contact_fields": ["channel", "value", "url", "source_id"],
                "channel_fields": ["platform", "name", "url", "verification", "source_id"],
                "makers": data["makers"]}
    files[ROOT / "docs/assets/data/makers.json"] = json.dumps(exported, ensure_ascii=False, indent=2) + "\n"
    outdated = []
    for path, value in files.items():
        if path.suffix == ".md":
            def icon(match):
                svg = Path(material.__file__).parent / "templates/.icons/material" / f"{match[1]}.svg"
                return '<span class="md-icon" aria-hidden="true">' + svg.read_text().strip() + '</span>'
            value = re.sub(r":material-([a-z0-9-]+):", icon, value)
        if check:
            if not path.exists() or path.read_text() != value:
                outdated.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value)
    if outdated:
        raise SystemExit("Regenerate maker pages: " + ", ".join(outdated))
    print(f"{'Checked' if check else 'Rendered'} {len(data['makers'])} maker profiles and directory; sources validated.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated files without modifying them")
    render(parser.parse_args().check)
